const api = {
  getConfig: jest.fn().mockResolvedValue({ root_dir: '/test/manga' }),
  updateConfig: jest.fn().mockResolvedValue({ success: true }),
  scan: jest.fn().mockResolvedValue({ scanned: 5, message: '扫描完成' }),
  getArchives: jest.fn().mockResolvedValue([]),
  getArchive: jest.fn().mockResolvedValue({}),
  getPages: jest.fn().mockResolvedValue({ archive: {}, pages: [], read_page: 0 }),
  deleteArchive: jest.fn().mockResolvedValue({ success: true }),
  getHistory: jest.fn().mockResolvedValue([]),
  saveHistory: jest.fn().mockResolvedValue({ success: true }),
  deleteHistory: jest.fn().mockResolvedValue({ success: true }),
  clearHistory: jest.fn().mockResolvedValue({ success: true }),
  getTags: jest.fn().mockResolvedValue([]),
  getNamespaces: jest.fn().mockResolvedValue([]),
  createTag: jest.fn().mockResolvedValue({ id: 1 }),
  updateTag: jest.fn().mockResolvedValue({ success: true }),
  deleteTag: jest.fn().mockResolvedValue({ success: true }),
  assignTag: jest.fn().mockResolvedValue({ success: true }),
  removeTag: jest.fn().mockResolvedValue({ success: true }),
  getCategories: jest.fn().mockResolvedValue([]),
  createCategory: jest.fn().mockResolvedValue({ id: 1 }),
  updateCategory: jest.fn().mockResolvedValue({ success: true }),
  deleteCategory: jest.fn().mockResolvedValue({ success: true }),
  assignCategory: jest.fn().mockResolvedValue({ success: true }),
  removeCategory: jest.fn().mockResolvedValue({ success: true }),
  getSettings: jest.fn().mockResolvedValue({}),
  updateSettings: jest.fn().mockResolvedValue({ success: true }),
  getStats: jest.fn().mockResolvedValue({ archives: 0, tags: 0, categories: 0, history: 0, total_pages: 0, total_size: 0 }),
  exportBackup: jest.fn().mockReturnValue('/api/backup'),
  importBackup: jest.fn().mockResolvedValue({ success: true }),
};

export default api;
